/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import { a } from '@react-spring/three';
import { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';

import santaScene from '../assets/3d/santa.glb';

const Santa = (props) => {
  const santaRef = useRef();

  const { nodes, materials } = useGLTF(santaScene);
  return (
    <a.group ref={santaRef} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rp_posed_00347_29.geometry}
        material={materials.rp_posed_00347_29_mat_temp}
        scale={0.01}
      />
    </a.group>
  );
};

export default Santa;
